Repository lucy-kim04/4-favpic-team1-FE, pull requests merged in 2025-02, with the labels that each got.

#1 [조형민] hotfix: 폴더 생성
  .gitignore
  assets/images/.gitkeep
  components/atoms/.gitkeep
  hooks/.gitkeep
Labels: hotfix

#4 [조형민] refactor(teacher): global.css, tailwind.config.mjs 일부 수정
  app/globals.css
  tailwind.config.mjs
Labels: chore

#9 [조형민] Feature/7/유저인증
  .vscode/settings.json
  api/client.js
  api/users/users.api.js
  app/(providers)/(root)/auth/log-in/page.jsx
  app/(providers)/(root)/auth/sign-up/page.jsx
  app/(providers)/(root)/layout.jsx
  app/(providers)/layout.jsx
  app/favicon.ico
  app/globals.css
  app/icon.png
  app/layout.js
  app/layout.jsx
  assets/fonts/baskin/br_b.otf
  assets/fonts/baskin/br_r.otf
  assets/images/ic-eye-disable.png
  assets/images/ic-eye-off-disable.png
  assets/images/ic-eye-off.png
  assets/images/ic-eye.png
  assets/images/ic-notification.png
  assets/images/ic-search.png
  assets/images/ic-x.png
  assets/images/logo.png
  contexts/AuthContext.jsx
  tailwind.config.mjs
Labels: feat

#10 feat: card level flag
  components/atoms/GradeCardBadge.jsx
  components/atoms/GradeMyCardCount.jsx
  components/atoms/SaleStatusChip.jsx
Labels: feat

#16 [김희주] feat: Dropdown 등급 구현 수정본
  components/atoms/Dropdown.jsx
Labels: feat

#20 [조형민] Card컴포넌트 구현 외 Feature/14
  app/(providers)/(root)/auth/log-in/page.jsx
  app/(providers)/(root)/layout.jsx
  app/(providers)/(root)/my-cards/gallery/page.jsx
  components/atoms/Button.jsx
  components/atoms/Gnb.jsx
  components/atoms/Logo.jsx
  components/molecules/CardBottom.jsx
  components/molecules/CardTop.jsx
  components/organism/Card.jsx
  tailwind.config.mjs
Labels: fix, feat

#25 [김희주] feat: Dropdown 구현
  components/atoms/Dropdown.jsx
Labels: feat

#26 [조형민] 페이지 컨테이너, 타이틀 컴포넌트, 마이갤러리 페이지 등 Feature/21
  api/cards/cards.api.js
  app/(providers)/(root)/my-cards/gallery/page.jsx
  app/(providers)/(root)/page.js
  assets/data/mock.js
  components/atoms/Gnb.jsx
  components/atoms/PageContainer.jsx
  components/atoms/TitleText.jsx
  components/molecules/CardBottom.jsx
  components/molecules/CardTop.jsx
  components/molecules/Title.jsx
  components/organisms/Card.jsx
  components/organisms/CardList.jsx
  components/organisms/MarketPlaceHeader.jsx
  components/organisms/MyGalleryHeader.jsx
  next.config.mjs
Labels: feat

#28 [김희주] Feature: dropdown component
  app/(providers)/(root)/auth/dropdown/page.js
  components/atoms/Dropdown.jsx
Labels: feat

#29 [조형민] shop API, Card컴포넌트 수정, 마켓플레이스 페이지 구현 Feature/27
  api/cards/cards.api.js
  api/shops/shops.api.js
  app/(providers)/(root)/page.js
  components/atoms/Dropdown.jsx
  components/atoms/Gnb.jsx
  components/molecules/CardBottom.jsx
  components/molecules/CardTop.jsx
  components/organisms/Card.jsx
  components/organisms/CardList.jsx
  components/organisms/MarketPlaceHeader.jsx
  components/templates/MarketPlace.jsx
  constant/index.js
Labels: feat

#34 [김희주] Feat:다시 선택 시 reset 기능 추가
  components/atoms/Dropdown.jsx
Labels: feat

#35 [조형민] feat: 로그인/회원가입 구현
  api/client.js
  api/users/users.api.js
  app/(providers)/(root)/auth/log-in/page.jsx
  app/(providers)/(root)/auth/sign-up/page.jsx
  components/atoms/Gnb.jsx
  components/templates/MarketPlace.jsx
  contexts/AuthContext.jsx
Labels: feat

#37 [김희주] feature: main화면 dropdown component prop 수정, component 수정
  components/atoms/Dropdown.jsx
  components/templates/MarketPlace.jsx
Labels: feat

#39 [조형민] feat: 포토카드 생성하기 구현
  api/cards/cards.api.js
  app/(providers)/(root)/my-cards/gallery/create/page.jsx
  app/(providers)/(root)/my-cards/gallery/page.jsx
  components/molecules/InputUpload.jsx
  components/organisms/MyGalleryHeader.jsx
  components/templates/MyGallery.jsx
Labels: feat

#40 [김희주] feat:setSelectedOption 오류 수정, 선택된 option배경 추가
  components/atoms/Dropdown.jsx
Labels: feat

#57 [조형민] 마이갤러리 구현, 토큰 리프레시 수정 Feature/53
  api/cards/cards.api.js
  api/users/users.api.js
  app/(providers)/(root)/[shopId]/page.jsx
  app/(providers)/(root)/my-cards/gallery/[cardId]/page.jsx
  app/(providers)/(root)/my-cards/gallery/create/page.jsx
  assets/images/ic-dropdown.png
  components/atoms/Dropdown.jsx
  components/atoms/Gnb.jsx
  components/molecules/CardDetailBottom.jsx
  components/molecules/CardDetailTop.jsx
  components/molecules/InputSearch.jsx
  components/molecules/UserCardsSummary.jsx
  components/organisms/Card.jsx
  components/organisms/CardDetail.jsx
  components/templates/Detail.jsx
  components/templates/MarketPlace.jsx
  components/templates/MyGallery.jsx
  components/templates/ShopDetail.jsx
Labels: refactor, fix, feat

#61 [조형민] 확인 모달창, 성공/실패 결과 페이지 구현 Feature/60
  app/(providers)/(root)/my-cards/gallery/create/page.jsx
  app/(providers)/(root)/result/page.jsx
  components/atoms/ ModalBackGround.jsx
  components/atoms/ResultContent.jsx
  components/atoms/ResultTitle.jsx
  components/molecules/CardDetailBottom.jsx
  components/molecules/ConfirmModal.jsx
  components/molecules/ResultCreateCard.jsx
  components/molecules/ResultCreateShop.jsx
  components/molecules/ResultProposeExchange.jsx
  components/molecules/ResultPurchase.jsx
  components/templates/MarketPlace.jsx
  libs/lineBreakText.js
Labels: feat

#68 [김희주] feat: dropdown tablet 반응형 추가
  components/atoms/Dropdown.jsx
  components/templates/MarketPlace.jsx
Labels: feat

#85 [김주영] feat: 포인트 팝업, 알림메시지 팝업
  components/atoms/Gnb.jsx
  components/atoms/NotificationPopup.jsx
  components/atoms/PointPopup.jsx
  components/templates/MarketPlace.jsx
Labels: feat

#89 [조형민] 충돌 해결, 카드 마우스 오버 효과 적용 Feature/77
  app/(providers)/(root)/my-cards/gallery/create/page.jsx
  app/(providers)/(root)/result/page.jsx
  components/atoms/Button.jsx
  components/atoms/Loader.jsx
  components/molecules/CardDetailBottom.jsx
  components/molecules/ResultStopSales.jsx
  components/organisms/Card.jsx
  components/templates/CardDetailModalForSale.jsx
  package-lock.json
  package.json
  tailwind.config.mjs
Labels: fix, feat
